-- CORRER PRIMERO SOLAMENTE ESTA PARTE DEL SCRIPT
-- SI SE CORRE TODO EL SCRIPT, NO FUNCIONA

ALTER TABLE Direccion
ALTER COLUMN idPersona UNIQUEIDENTIFIER NOT NULL;

--

ALTER TABLE Direccion
ADD CONSTRAINT PK_Direccion PRIMARY KEY (idPersona);

ALTER TABLE Persona
ALTER COLUMN idDatosAuditoria UNIQUEIDENTIFIER NOT NULL;

ALTER TABLE Usuario
ALTER COLUMN contraseña VARCHAR(128) NOT NULL;